### ISSUE TITLE
Organizations extension fails with KC_HTTP_RELATIVE_PATH not /auth

### ISSUE THREAD

**Issue by KDMRyanT** [p2-inc/keycloak-ui#8] opened 2022-10-20 15:52 UTC
https://github.com/p2-inc/phasetwo-containers/issues/2

Hello I reported the following error that I have on phasetwo-containers.  When using the phasetwo theme for the admin console, showing the Organizations extension - when clicking on "Organizations" I get the following error:
![keycloak-p2inc-organizations-theme-e map-error](https://user-images.githubusercontent.com/105240774/196997072-71c8f729-e91c-4bcb-aeb6-04623e743bc2.jpg)
Is there any fixes for this?  Is this a known error?

I have been working with another extension in p2inc/containers compiled outside of those extensions contained within the container.  This extension would not work with new version of keycloak-theme and I needed to specifically use old keycloak theme ( admin console ) for it to run properly.  Is this the same kind of thing/error?  Please advise.

**Comment by xgp** [comment] 2022-10-20 16:09
It's a new one. The phasetwo self-serve clusters are running the same image, so I'm not sure what's going on. Is there more information when you open the console?

**Comment by xgp** [comment] 2022-10-20 16:13
Also, I'm not able to reproduce locally when running in docker:
```
docker run --name phasetwo_test -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HTTP_RELATIVE_PATH=/auth quay.io/phasetwo/phasetwo-keycloak:19.0.3-alpha start-dev
```
and then accessing the console via: http://127.0.0.1:8080/auth/admin/master/console/

**Comment by xgp** [comment] 2022-10-20 16:27
Check that you've got the correct hash pulled sha256:329ea352d82f6c220dfe3a0d1cde68d64b0e05c5eeafb42dde4a857199d8bf1e

**Comment by KDMRyanT** [comment] 2022-10-20 17:58
@xgp I have checked my running container and it has the following image hash
sha256:e0a7298b0bed71da8857fbd282113fccb254feb272c2c20a4b7c291d1b5e54d1

On running the docker pull command again locally I have the following:
docker pull quay.io/phasetwo/phasetwo-keycloak:19.0.3-alpha
19.0.3-alpha: Pulling from phasetwo/phasetwo-keycloak
Digest: sha256:329ea352d82f6c220dfe3a0d1cde68d64b0e05c5eeafb42dde4a857199d8bf1e
Status: Image is up to date for quay.io/phasetwo/phasetwo-keycloak:19.0.3-alpha
quay.io/phasetwo/phasetwo-keycloak:19.0.3-alpha

On inspection of the downloaded image in docker id property value:
sha256:e0a7298b0bed71da8857fbd282113fccb254feb272c2c20a4b7c291d1b5e54d1

am I missing something? Could it be that accessing the console through https connection or hostname connection cause the issue? In your parameters the KC_HTTP_RELATIVE_PATH?

**Comment by xgp** [comment] 2022-10-20 18:05
Are you able to try with `KC_HTTP_RELATIVE_PATH=/auth`? I've never tried it without that.

Also, anything from the devtools Console or Network tab would be helpful, as I've never seen that error before.

**Comment by KDMRyanT** [comment] 2022-10-20 18:26
Hello @xgp that seems to have fixed the issue - I removed the container and restarted with KC_HTTP_RELATIVE_PATH=/auth and this now works.  Going to the organizations tab with master realm keycloak admin theme set to phasetwo.v2.

**Comment by xgp** [comment] 2022-10-20 18:28
Thanks. I'll keep this one open until I fix that. Thanks for debugging with me.

**Comment by xgp** [comment] 2022-10-20 18:30
@pnzrr It's possible that Keycloak will be deployed with a different "relative path" than we use by default. That means the base url could be `https://foo.com/auth/` or `https://foo.com/bar/` or `https://foo.com/`. I think the failure is in how we create the base url for the organizations API calls. Can you take a look?

**Comment by aceat64** [comment] 2022-11-02 21:05
I did some digging and found the issue:

https://github.com/p2-inc/keycloak-ui/blob/19.0.3_orgs/apps/admin-ui/src/orgs/useOrgFetcher.ts#L23
```typescript
const baseUrl = `${AUTH_URL}/realms/${realm}`;
```

Instead of `AUTH_URL` this should be `environment.authUrl`. The import from `../environment` will need to be updated as well.

**Comment by xgp** [comment] 2022-11-13 13:17
This is now fixed in https://github.com/p2-inc/keycloak-ui/blob/20.0.1_orgs/apps/admin-ui/src/environment.ts. Thanks for the help @aceat64

**Closed by xgp** 2022-11-13 13:17 UTC
Labels: bug, priority
